# Dependencies
markdown:	kramdown
# Permalinks
permalink:	:title/

# Setup
title:            취향의 흔적
tagline:          'blog'
description:      'My personal blog.'
url:              http://resistan.com
baseurl:          
commentsystem:    disqus
disqus:           resistan
include:          [_pages]
default_locale:   "ko"

author:
  name:           resistan
  url:            https://resistan.com

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            https://lh3.googleusercontent.com/xI9Ts2HUpx-eWNCCWGyKAdhdMypoz_6X1R1ySpouzfrEvo4DWeRSfAqoB4m66yw7yippC8S-ptwph0IzX3Odd5HkobAyT_JShR3NDwGEctejctFfhgMYosIcNgfuIYxnhH5aupIkQ-EJmq27c784Af7jsFoqj_famaOFpJ22DSKMniWNbhJ-Tn8xHKxhJXdUr9IongUBEHWjTW0dvXJS9ZbeAoJ1zbY6ZVDDtie0zwp9Zv7DDhwOJeGwkLmgojFYrrSPt_TbdIwMP0Q0PvD0N9lqoyKSwmIuKwS7zbRv_ps48wJQKJ_4QfraBh5IbKotX01ea7SR4banyTtmyqxzPN2KicGZfZmhuq8nJlR2RsRH4Cl1wDPQlw8Y187LhSGPIAl-6QIkdwJ4sa04LDjO3wat5KjBGWX_5y6w-WMebu6nf58TJuI1J9YcGD6kFst5BwuHXXm7EMBvapopbI9uyqTWoa1ogGCu4oq4YQPQt5k-kEZ9NsgylgURiHVJ_qE31vDWcVeu1JftI0NW62QPxADReOH4fJHnYCQc3Cun4XWrg9-CqewgtVnHoMcNOKVXBV0z6WL76UmFFYeiGLtWFA-pW2mOFg1dhMtyQudDea7i-GRAeVQxhfs4Jna0sSv3-OFuUAPB-wQXp-TJiUEwSlfuP4S89bjM7aFASlCEDJJXmQ4=w1789-h1007-no

social:
  - icon:         facebook
    url:          https://facebook.com/hj.soif
    desc:         Follow me on facebook
  - icon:         twitter
    url:          https://twitter.com/resistan
    desc:         Follow me on twitter
  - icon:         github
    url:          https://github.com/resistan
    desc:         Fork me on github
  # - icon:         googleplus-alt
  #   url:          https://google.com/+IanCamporezBrunelli
  #   desc:         Add me on google+
  - icon:         feed
    url:          http://resistan.github.io/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        "처음"
    url:          /
  - title:        "소개"
    url:          /about-me
  - title:       "전체 글 모음"
    url:          /archives
  # - title:       "방명록"
  #   url:          /guestbook
  - title:       "개발자 좀 살려주세요"
    url:          /savethedeveloper/

copyright:
  author:         resistan
  url:            http://resistan.com
  type_title:     Some rights reserved
  type_url:       https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ko

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  UA-251544-2

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576

gems: [jekyll-paginate]